#include <Arduino.h>

#ifndef __PCP_SENSOR_H
#define __PCP_SENSOR_H

#define SENSOR_ROW_OUT_START 30
#define SENSOR_COL_IN_START 31
#define DEBOUNCE_TIME 2

void sensor_setup();
void sensor_refresh();
boolean sensor_read(byte sensor);
boolean sensor_read_latch(byte sensor);
boolean sensor_read_latch_inverse(byte sensor);
byte trough_count(void);

#define SENSOR_dt11         !sensor_read(0)
#define SENSOR_dt21         !sensor_read(1)
#define SENSOR_jam          sensor_read(2)
#define SENSOR_trough_ready sensor_read(3)
#define SENSOR_fl1          sensor_read(4)
#define SENSOR_fl2          sensor_read(5)
#define SENSOR_start        sensor_read(6)
#define SENSOR_dt12         !sensor_read(7)
#define SENSOR_dt22         !sensor_read(8)
#define SENSOR_kick         sensor_read(9)
#define SENSOR_star_roll    sensor_read(10)
#define SENSOR_sling1       sensor_read(11)
#define SENSOR_sling2       sensor_read(12)
#define SENSOR_scoop        !sensor_read(13)
#define SENSOR_dt13         !sensor_read(14)
#define SENSOR_dt23         !sensor_read(15)
#define SENSOR_pop1         sensor_read(16)
#define SENSOR_pop2         sensor_read(17)
#define SENSOR_pop3         sensor_read(18)
#define SENSOR_tilt         sensor_read(19)
#define SENSOR_large_rect   sensor_read(20)
#define SENSOR_trough7      sensor_read(21)
#define SENSOR_trough6      sensor_read(22)
#define SENSOR_trough5      sensor_read(23)
#define SENSOR_trough4      sensor_read(24)
#define SENSOR_trough3      sensor_read(25)
#define SENSOR_trough2      sensor_read(26)
#define SENSOR_trough1      sensor_read(27)
#define SENSOR_roll7        sensor_read(28)
#define SENSOR_roll6        sensor_read(29)
#define SENSOR_roll5        sensor_read(30)
#define SENSOR_roll4        sensor_read(31)
#define SENSOR_roll3        sensor_read(32)
#define SENSOR_roll2        sensor_read(33)
#define SENSOR_roll1        sensor_read(34)
#define SENSOR_roll14       sensor_read(35)
#define SENSOR_roll13       sensor_read(36)
#define SENSOR_roll12       sensor_read(37)
#define SENSOR_roll11       sensor_read(38)
#define SENSOR_roll10       sensor_read(39)
#define SENSOR_roll9        sensor_read(40)
#define SENSOR_roll8        sensor_read(41)
#define SENSOR_stand3       sensor_read(42)
#define SENSOR_stand2       sensor_read(43)
#define SENSOR_stand1       sensor_read(44)
#define SENSOR_rect3        sensor_read(45)
#define SENSOR_rect2        sensor_read(46)
#define SENSOR_rect1        sensor_read(47)
#define SENSOR_roll15       sensor_read(48)
// [...]
#define SENSOR_rr1          sensor_read(52)
#define SENSOR_rr2          sensor_read(53)
#define SENSOR_stand5       sensor_read(54)
#define SENSOR_stand4       sensor_read(55)




#define LATCH_dt11         sensor_read_latch_inverse(0)
#define LATCH_dt21         sensor_read_latch_inverse(1)
#define LATCH_jam          sensor_read_latch(2)
#define LATCH_trough_ready sensor_read_latch(3)
#define LATCH_fl1          sensor_read_latch(4)
#define LATCH_fl2          sensor_read_latch(5)
#define LATCH_start        sensor_read_latch(6)
#define LATCH_dt12         sensor_read_latch_inverse(7)
#define LATCH_dt22         sensor_read_latch_inverse(8)
#define LATCH_kick         sensor_read_latch(9)
#define LATCH_star_roll    sensor_read_latch(10)
#define LATCH_sling1       sensor_read_latch(11)
#define LATCH_sling2       sensor_read_latch(12)
#define LATCH_scoop        sensor_read_latch_inverse(13)
#define LATCH_dt13         sensor_read_latch_inverse(14)
#define LATCH_dt23         sensor_read_latch_inverse(15)
#define LATCH_pop1         sensor_read_latch(16)
#define LATCH_pop2         sensor_read_latch(17)
#define LATCH_pop3         sensor_read_latch(18)
#define LATCH_tilt         sensor_read_latch(19)
#define LATCH_large_rect   sensor_read_latch(20)
#define LATCH_trough7      sensor_read_latch(21)
#define LATCH_trough6      sensor_read_latch(22)
#define LATCH_trough5      sensor_read_latch(23)
#define LATCH_trough4      sensor_read_latch(24)
#define LATCH_trough3      sensor_read_latch(25)
#define LATCH_trough2      sensor_read_latch(26)
#define LATCH_trough1      sensor_read_latch(27)
#define LATCH_roll7        sensor_read_latch(28)
#define LATCH_roll6        sensor_read_latch(29)
#define LATCH_roll5        sensor_read_latch(30)
#define LATCH_roll4        sensor_read_latch(31)
#define LATCH_roll3        sensor_read_latch(32)
#define LATCH_roll2        sensor_read_latch(33)
#define LATCH_roll1        sensor_read_latch(34)
#define LATCH_roll14       sensor_read_latch(35)
#define LATCH_roll13       sensor_read_latch(36)
#define LATCH_roll12       sensor_read_latch(37)
#define LATCH_roll11       sensor_read_latch(38)
#define LATCH_roll10       sensor_read_latch(39)
#define LATCH_roll9        sensor_read_latch(40)
#define LATCH_roll8        sensor_read_latch(41)
#define LATCH_stand3       sensor_read_latch(42)
#define LATCH_stand2       sensor_read_latch(43)
#define LATCH_stand1       sensor_read_latch(44)
#define LATCH_rect3        sensor_read_latch(45)
#define LATCH_rect2        sensor_read_latch(46)
#define LATCH_rect1        sensor_read_latch(47)
#define LATCH_roll15       sensor_read_latch(48)
// [...]
#define LATCH_rr1          sensor_read_latch(52)
#define LATCH_rr2          sensor_read_latch(53)
#define LATCH_stand5       sensor_read_latch(54)
#define LATCH_stand4       sensor_read_latch(55)

#endif
